### PR TITLE
Task 1195: Disfluent to fluent sentence conversion

### PR DESCRIPTION
**Pull request by ashok-arjun**
Dataset: https://arxiv.org/abs/2106.04016

Task:

Given a disfluent sentence, convert to its equivalent fluent form

### CODE REVIEW

**Comment by Palipoor** [comment]
Hi!
This looks good to me, just a few comments:
1. For the category, maybe "Text Modification" is better.
2. Please add a full stop at the end of the description. Also, it'd be good if you could make it a little bit longer, so it is more informative.
3. In the second and third negative examples, you can change this in the explanation: " but the output does not." -> "but the output does not reflect that".

**Comment by ashok-arjun** [comment]
> Hi! This looks good to me, just a few comments:
> 
> 1. For the category, maybe "Text Modification" is better.
> 2. Please add a full stop at the end of the description. Also, it'd be good if you could make it a little bit longer, so it is more informative.
> 3. In the second and third negative examples, you can change this in the explanation: " but the output does not." -> "but the output does not reflect that".

@Palipoor Thanks for the review, I've done all three

**Comment by Palipoor** [comment]
Thanks! Looks good to me.

**Comment by ashok-arjun** [comment]
@danyaljj Can you please verify and merge this?

**Review by Palipoor — APPROVED** [review]

**Pull request merged**
