### PR TITLE
Task1165-1166: ENTAM dataset

### PR DESCRIPTION
**Pull request by ashok-arjun**
Eng<->Tamil Translation

2 Tasks in total.

Dataset: https://ufal.mff.cuni.cz/~ramasamy/parallel/html/

### CODE REVIEW

**Comment by ashok-arjun** [comment]
@danyaljj @swarooprm I'm not sure if anyone knows Tamil here. How can this PR be reviewed?

**Comment by danyaljj** [comment]
@Mirzyaaliii @cosmicishan @aarunku5 @shailaja183  wondering any of you speak Tamil?

**Comment by Mirzyaaliii** [comment]
> @Mirzyaaliii @cosmicishan @aarunku5 @shailaja183 wondering any of you speak Tamil?

@danyaljj Not me.

**Comment by cosmicishan** [comment]
> @Mirzyaaliii @cosmicishan @aarunku5 @shailaja183 wondering any of you speak Tamil?

Not me.

**Comment by aarunku5** [comment]
Yes I do, I can review it

**Comment by ashok-arjun** [comment]
@danyaljj Can this PR be reviewed by @aarunku5 ?

**Comment by aarunku5** [comment]
1165
Change it to "passage" in the definition, some of the instances have multiple sentences.
" keep numbers as it is"-->"retain numbers as is"
You can also remove the bit about sentence case, there's no explicit capitalization in Tamil.

1166
Change it to "passage" in the definition
" keep numbers as it is"-->"retain numbers as is"
Add an extra line in the definition for what to do in the case of (a), (b), (c)... list options present in the output. The Tamil letter order is used in the corresponding input.

For both the tasks though, there are some issues in the translation for both examples and instances i.e.:

1165:
P2- the translation of the second sentence alters its meaning
P3- the organization is translated incorrectly- doesn't capture "reformist", and the use of "pazha" for old is wrong (the organization needs to be properly translated as: pazhamaivaadhar seerthirthavaadhigal thollarargal sangam)
N1- theeya vettai as witchcraft is not a correct translation, nor is hand-in-hand translated properly
N2- The translation actually changes to state wide, not country wide

1166:
P1- the word diplomatic in the text refers to the Consulate, but has been translated as “diplomatic allusion”, also the use of “grumbled” in the translation though literally correct needs to be translated as “criticized” in this context
P3- The Tamil input is more elaborate in explaining the context than the English output
N1- this is more like a transliteration of a list of names than translation

These problems repeat in several of the instances as well, and it essentially stems from the nature of the translation- it's a word for word literal translation meaning that  the context of the translation is not properly captured- and the grammatical structure is a bit unorthodox- you would probably not see certain phrase structures from a native Tamil speaker. So while the translation is meaningful say ~70%(?) of the time, it isn’t  necessarily contextually or grammatically error-free.

I would say that a manual review of all instances would probably be needed to alter the translations in both the tasks to ensure this doesn’t happen.

**Comment by ashok-arjun** [comment]
@aarunku5 Thanks for the review. What do you suggest I do? Would it be better if I frame this task as a Yes/No task to predict whether it is a the correct translation?

**Comment by aarunku5** [comment]
You can make it a yes/no task, but you would still have to comb over the instances to ensure that they're properly labelled. If you can do that and resubmit, I can take a look at it.

**Comment by ashok-arjun** [comment]
Closing this PR since I am discarding this task.

**Pull request closed without merging**
