### PR TITLE
task 868-871 CFD, MSMARCO

### PR DESCRIPTION
**Pull request by ujjwalaananth**
README updated, 4 tasks added.

### CODE REVIEW

**Comment by danyaljj** [comment]
Thanks @ujjwalaananth! 

Looks like the tests are failing. Could you check the errors?

**Comment by ujjwalaananth** [comment]
> Thanks @ujjwalaananth!
> 
> Looks like the tests are failing. Could you check the errors?

I believe it was due to someone not updating the Readme with the names of their json file. I can try to pull and recommit my changes, assuming the Readme is now correctly updated.

**Comment by danyaljj** [comment]
It can't be someone else since the tests on the main branch are not failing. 

Now the issue is that your branch is not correctly merged with the main branch. On your side, you'd need to manually merge the latest changes with your local branch so that we can re-trigger the tests.

**Comment by aarunku5** [comment]
> It can't be someone else since the tests on the main branch are not failing.
> 
> Now the issue is that your branch is not correctly merged with the main branch. On your side, you'd need to manually merge the latest changes with your local branch so that we can re-trigger the tests.

@ujjwalaananth Can you merge your repo and commit again? Thanks!

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Comment by aarunku5** [comment]
> Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

@ujjwalaananth can you please update your files based on the previous comments?

**Comment by danyaljj** [comment]
Moved the tasks to #490

**Pull request closed without merging**
