### PR TITLE
Tasks 917-921: CoQA Dataset, code_x_glue Dataset 

### PR DESCRIPTION
**Pull request by ShashankDavalgi**

### CODE REVIEW

**Comment by danyaljj** [comment]
@ShashankDavalgi can you please merge your PR with the main branch? 

@liusiyi641 wondering if you can review this PR?

**Review by liusiyi641 — COMMENTED** [review]
It generally looks good to me! A few comments: (1). Task 917 in definition: "a question" -> "questions". (2) Maybe a more specific definition for task919, like what constitutes a bad "incorrect answer" and what constitutes a good one just like the definitions from other tasks? I'm a bit confused about the positive/negative examples there, and the explanation for both negative examples are the same.

**Comment by ShashankDavalgi** [comment]
@liusiyi641 Is it OK if I do it after my mid terms during the fall break?

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Comment by swarooprm** [comment]
@ShashankDavalgi, could you address the reviewer concerns so that we can move ahead with this PR?

**Review by swarooprm — APPROVED** [review]

**Comment by swarooprm** [comment]
Reviews: https://github.com/swarooprm/CSE576HW/pull/81

**Pull request merged**
