### PR TITLE
Tasks 1218-1282: TED translation task for an additional 65 language directions

### PR DESCRIPTION
**Pull request by davidstap**
As suggested by @swarooprm in #364 I have created 65 additional translation tasks. The structure is identical to #364, which  is approved and merged, so reviewing should be simple.

### CODE REVIEW

**Comment by aarunku5** [comment]
Thanks, everything looks good, just one comment: since the tasks are templated, it would probably be good to have explanations a little more customized in some places- like a line saying the number is correctly translated or the name is retained incorrectly or tense is correctly translated. Take a look at #66 for a reference.

**Comment by davidstap** [comment]
Thanks for your review. Indeed the tasks are templated, and I agree it would be great to have some meaningful examples. I noticed the deadline for task pull requests is October 15th, but unfortunately I'm busy with another deadline and I do not have time before next week. I could add some (20? 30? 40?) non-template explanations by then, but not sure if this is allowed. Alternatively we can merge as it is, or delete the tasks. What should I do?

**Comment by danyaljj** [comment]
Please make sure to set the `"Categories": [""]` and `"Domains": [""]` fields according to [the taxonomy presented here](https://github.com/allenai/natural-instructions-expansion/blob/master/doc/task-hierarchy.md).

**Comment by danyaljj** [comment]
After October 15 we will start analyses on the data up to that date. However, you should feel free to send PRs with new data and fixes. The repository will remain open and we will continue to update the data, in order to improve/expand it.

**Comment by davidstap** [comment]
Right, then I will improve this PR next Thursday / Friday. Thanks for the info.

**Comment by danyaljj** [comment]
@davidstap checking if you will get a chance to revise this PR soon.

**Comment by davidstap** [comment]
I have some time for this tomorrow :)

**Comment by davidstap** [comment]
* As suggested by @aarunku5, I have added some hand-crafted explanations. Specifically, I have included one positive and one negative hand-crafted example for tasks 1218-1238, and for tasks 1247, 1256, 1265, 1274 (the latter four are all translations into English).
* The TED dataset spans a wide range of subjects and domains, but this metadata is not in the dataset. Therefore I unfortunately cannot map instances to `Domains`.

**Comment by danyaljj** [comment]
Thanks! Could you merge the PR with the main branch as well?

**Comment by davidstap** [comment]
I have merged the main branch now, but unfortunately I was unable to do it in this PR, so I have created a new one (see #478). I will close this one now, apologies for the mess.

**Pull request closed without merging**
